#!/bin/bash
set -e

case "$1" in
    remove|upgrade)
        systemctl stop ups-pi-node.service || true
        systemctl stop ups-pi-node-helper.service || true
        systemctl stop ups-pi-node-hotspot-fallback.timer || true
        systemctl disable ups-pi-node.service || true
        systemctl disable ups-pi-node-helper.service || true
        systemctl disable ups-pi-node-hotspot-fallback.timer || true
        rm -f /etc/nginx/sites-enabled/ups-pi-node
        systemctl reload nginx || true
        ;;
esac

exit 0
